services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finan_object_lara_app
    volumes:
      - .:/var/www
    networks:
      - laravel_network_finan_object
    depends_on:
      - mysql
    ports:
      - "5173:5173"

  nginx:
    image: nginx:alpine
    container_name: finan_object_lara_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network_finan_object
    depends_on:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: finan_object_lara_mysql
    volumes:
      - mysql_data_finan_object:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finan_object_lara
      MYSQL_USER: finan_object_lara
      MYSQL_PASSWORD: finan_object_lara
    ports:
      - '3339:3306'
    expose:
      - 3306
    networks:
      - laravel_network_finan_object

networks:
  laravel_network_finan_object:
    driver: bridge

volumes:
  mysql_data_finan_object:
